const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, ShadingType, LevelFormat, AlignmentType, BorderStyle, Footer, PageNumber, ImageRun, PageBreak } = require('docx');
const W = 10206, r = (t, o = {}) => new TextRun({ text: t, ...o });
const P = (x, o = {}) => new Paragraph({ spacing: { after: 80, line: 290 }, ...o, children: (Array.isArray(x) ? x : [x]).map(y => typeof y === 'string' ? r(y) : y) });
const H1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 180, after: 70 }, keepNext: true, children: [r(t)] });
const H2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 110, after: 50 }, keepNext: true, children: [r(t)] });
const B = t => r(t, { bold: true });
const bul = x => new Paragraph({ numbering: { reference: 'b', level: 0 }, spacing: { after: 40, line: 256 }, children: (Array.isArray(x) ? x : [x]).map(y => typeof y === 'string' ? r(y) : y) });
const bd = { style: BorderStyle.SINGLE, size: 4, color: 'C9C8C2' };
const cell = (t, w, h, hl) => new TableCell({ width: { size: w, type: WidthType.DXA }, borders: { top: bd, bottom: bd, left: bd, right: bd },
  shading: h ? { type: ShadingType.CLEAR, fill: '1F3A5F', color: 'auto' } : (hl ? { type: ShadingType.CLEAR, fill: 'E8EEF5', color: 'auto' } : undefined),
  margins: { top: 40, bottom: 40, left: 70, right: 70 }, children: String(t).split('\n').map(line => new Paragraph({ children: [r(line, { bold: h || hl, color: h ? 'FFFFFF' : undefined, size: 17 })] })) });
const table = (rows, cols, hl = []) => new Table({ width: { size: W, type: WidthType.DXA }, columnWidths: cols, rows: rows.map((rw, i) => new TableRow({ cantSplit: true, tableHeader: i === 0, children: rw.map((t, j) => cell(t, cols[j], i === 0, hl.includes(i))) })) });
const img = (f, w0, h0, wd = 640) => new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 }, keepNext: false, children: [new ImageRun({ type: 'png', data: fs.readFileSync('fig/' + f), transformation: { width: wd, height: Math.round(wd * h0 / w0) } })] });
const cap = t => P([r(t, { size: 15, italics: true, color: '52514E' })], { spacing: { after: 100 } });
const R = JSON.parse(fs.readFileSync('out/runs.json')); const X = JSON.parse(fs.readFileSync('out/extra_runs.json'));
const b = R.res.Base, d = R.res.Downside, a = R.res.Aggressive, c = R.res['CFO-capped'];
const f1 = v => (typeof v === 'number' ? v.toFixed(1) : v), pc = v => (v * 100).toFixed(1) + '%', f0 = v => v.toFixed(0);
const dim = f => { const bf = fs.readFileSync('fig/' + f); return [bf.readUInt32BE(16), bf.readUInt32BE(20)]; };
const be = R.be;
const kids = [
  new Paragraph({ spacing: { after: 30 }, children: [r('D7 · Integrated revenue plan, FY27–FY29', { bold: true, size: 32, color: '1F3A5F' })] }),
  P([r('Revenue Strategy Lead, Office of the CRO · Week 8, FY27 · Strata Sense Technologies is fictional; all data synthetic (MBA capstone). Model: D7_Integrated_Model.xlsx (one workbook owns every number in this memo). ₹ crore unless stated.', { italics: true, size: 16, color: '52514E' })],
    { border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '1F3A5F', space: 4 } } }),

  H1('1. Recommendation'),
  P([B('Approve the Base plan: ₹14.95 crore of incremental investment in FY27, inside the ₹15 crore envelope, 6 net new AEs from Q3 FY27, 3 channel roles, and a ₹2.82 crore reserve released at the Q2 review only if the triggers in section 12 are met. '),
    `It takes ARR from ₹310 crore to ₹${f1(b['ARR FY27'])} crore in FY27, ₹${f1(b['ARR FY28'])} crore in FY28 and ₹${f1(b['ARR FY29'])} crore in FY29. FY29 ARR clears the board path (₹521.9 crore) by ₹3.6 crore; FY28 growth meets 20%; FY27 growth is ${pc(b['Growth FY27'])}, ₹5.6 crore short of the 15% path. I am asking the board to accept that FY27 shortfall rather than fund it, for the reasons in section 4.`]),
  table([['Test (brief §6)', 'FY27', 'FY28', 'FY29', 'Result'],
    ['Closing ARR (₹ cr) / growth', `${f1(b['ARR FY27'])} / ${pc(b['Growth FY27'])}`, `${f1(b['ARR FY28'])} / ${pc(b['Growth FY28'])}`, `${f1(b['ARR FY29'])} / ${pc(b['Growth FY29'])}`, 'FY27 short of 15% (defended); FY28, FY29 met'],
    ['Net revenue retention', pc(b['NRR FY27']), '101.9%', pc(b['NRR FY29']), 'Short of 108% goal (defended)'],
    ['Gross margin after partner margin (floor 66%)', '68.6%', '67.5%', '67.7%', 'Met; depends on hardware attach falling (§6)'],
    ['CAC payback, margin-adjusted (≤ 30 every quarter; ≤ 24 by Q4 FY28)', 'Q1 31.0; Q2–Q4 28.1–29.4', 'Q4: 21.2', '17.3–20.6', 'One breach: Q1 FY27 (locked); exception requested'],
    ['S&M as % of ARR (≤ 30% by FY29)', '33.4%', '30.6%', '27.0%', 'Met'],
    ['Incremental investment (envelope ₹15 cr in FY27)', '14.95', '20.35', '26.55', 'Met'],
    ['Net new AEs (≤ 12 in FY27) / channel roles (≤ 6)', '6 / 3', '8 / 5', '6 / 6', 'Met'],
    ['EBITDA (₹ cr)', f1(b['EBITDA FY27']), f1(b['EBITDA FY28']), f1(b['EBITDA FY29']), 'Break-even in FY28'],
    ['Partner share of new-logo ARR (goal 25% by FY29)', '8.5%', '15.2%', '22.7%', 'Short (defended)']], [3300, 1650, 1400, 1400, 2456], []),
  P([B('Why this over doing nothing. '), `Doing nothing is not flat. If FY24–26 trends continue (win rate falling from 27% to 17%, NRR from 118% to 99%), ARR reaches ₹389 crore in FY29, ₹137 crore below the plan. The three-year investment of ₹61.9 crore pays back in ${f1(b['Investment payback FY29 (months)'])} months against that path, and in ${f1(b['Investment payback FY29 vs FY26-flat (months)'])} months even against the stricter test that credits only gains beyond FY26 performance.`], { spacing: { before: 100, after: 60 } }),
  img('arr_path.png', ...dim('arr_path.png')), cap('Exhibit 1. Closing ARR by scenario against the board path and the do-nothing path (model: Scenarios, Do_nothing).'),

  H1('2. How the model works'),
  P('One workbook owns every number. Deliverables D1–D6 now read from it; where an earlier deliverable showed a different figure (D2’s ₹46.5 crore new-logo need, D4’s scenarios, D6’s share denominator), this model supersedes it and the Checks sheet reconciles D6 partner ARR to the rupee.'),
  bul([B('Capacity. '), 'AEs are tracked in four tenure bands (0–6, 6–12, 12–24, 24+ months) with hiring, attrition by band and next-quarter backfill. Ramped-AE equivalents use D1’s measured productivity by tenure (weights 0 / 0.33 / 0.66 / 1.0), not management’s six-month ramp assumption, which the data rejected.']),
  bul([B('Bookings. '), 'Deals closed per quarter = ramped AEs × 5.4 deals carried at once × 3 ÷ sales cycle, capped by qualified pipeline supply. Direct ARR = deals × win rate × list deal × (1 − discount). All drivers move linearly from their FY26 actuals to each year’s scenario value, so improvement phases in. Q1 FY27 is the locked D4 forecast (₹8.71 crore), because that quarter was under way before the plan.']),
  bul([B('Channel. '), 'D6’s cohort model (activations, 15% / 60% / 100% ramp, ₹1.2 crore mature productivity) produces partner ARR, counted once: partner deals are not in direct bookings, and the AE’s 50% quota credit is compensation only.']),
  bul([B('ARR bridge and P&L. '), 'Quarterly: opening + direct + partner + expansion − contraction − churn − the Vajra re-tender = closing, with a zero-difference check every quarter. Revenue, gross margin (partner margin charged to cost of revenue for the floor test), S&M, R&D, G&A, EBITDA and CAC payback on the board-pack definition.']),
  bul([B('Controls. '), 'A scenario switch (Base, Downside, Aggressive, CFO-capped), five sensitivity shift cells plus a “share of plan delivered” lever, a Cascade sheet, and a Checks sheet with every guardrail. There are no plugs: every calculation cell is a formula or a labelled input traced in Appendix A.']),

  H1('3. The plan: five programmes and what each is expected to move'),
  table([['Programme', 'FY27 cost (₹ cr)', 'Driver moved in the model', 'FY26 → FY29 (Base)', 'Evidence'],
    ['1. Target the right accounts (tiering, programme reallocation)', 'within existing ₹24 cr budget', 'Win rate (mix); qualified pipeline supply', 'Mix +2.9 pts; supply 392 → 470 deals', 'D1 targeting root cause (₹8.0 cr); D2 back-test'],
    ['2. Win-rate and price discipline (value selling, battlecards, paid pilots, discount cap)', '0.92 + 0.64 + 0.32 reserve', 'Win rate; discount; deal size; cycle', 'Win 17.1% → 22.5%; discount 19.3% → 15%; cycle 8.1 → 7.3 months', 'D3 role-play and proposal; D5 win/loss; D1 discount creep (₹3.1 cr)'],
    ['3. Retention and Helix defence (squads, renewal protection, top-30 expansion, Vajra)', '1.52 + 0.80 + 0.82 + 0.9 + 1.6 reserve', 'Churn; contraction; expansion; Vajra loss probability', 'Churn 5.9% → 4.0%; expansion 8.1% → 10.5%; Vajra 45% → 20%', 'D1 Helix bundle (₹34 cr/yr, largest cause); Inject 2; Inject 4'],
    ['4. AE capacity (hiring to pipeline, retention pool)', '1.99 + 1.00', 'Ramped AEs; attrition', '64 → 83 AEs; attrition 29% → 20%', 'D1 tenure productivity; DR3 attrition'],
    ['5. Selective channel (SEA, Gulf, machine builders)', '2.44 + 0.40', 'Partner ARR', '₹2.6 cr → ₹19.7 cr', 'D6; Inject 3'],
    ['Enablers: RevOps and forecasting; sensor-agnostic readiness', '1.00 + 0.60', 'Forecast accuracy; hardware attach from Q4 FY27', 'Attach 1.48 → 1.05 per ₹1 of new + expansion ARR', 'D4; D1 SENSOR-REUSE']], [2500, 1300, 2100, 2300, 2006]),
  P([r('Honesty about attribution: the model attaches each programme to the drivers it should move, but the size of each driver change is a judgement anchored in D1–D6 evidence, not a measured effect. That is why section 8 tests how much of the planned improvement must be delivered before the plan stops paying back.', { italics: true })], { spacing: { before: 80 } }),

  H2('What the plan fixes from the D1 diagnosis'),
  table([['D1 root cause', 'ARR at stake (D1, per year)', 'Plan lever in the model', 'Recovered by FY29 (per year, approx.)', 'What is left'],
    ['Helix bundle: retention and new-logo losses in Helix-incumbent plants', '₹34.0 cr (25.6 retention + 8.4 new logo)', 'Churn 5.9% → 4.0%; Vajra plan; Helix-incumbent win held at 7%', '≈ ₹8.0 cr (1.9 pts × FY29 opening ARR) + ₹2.6 cr Vajra', '≈ ₹24 cr: a packaging and pricing decision (sensor-agnostic tier), not a sales fix; D8'],
    ['Expansion stall in non-Helix accounts', '₹9.9 cr', 'Expansion 8.1% → 10.5% of opening ARR', '≈ ₹10.1 cr', 'Recovered, if the top-30 programme works'],
    ['Wrong accounts and single-threaded deals', '₹8.0 cr', 'Tier mix +2.9 pts of win rate; pipeline supply', '≈ ₹8.8 cr', 'Recovered; depends on pipeline supply (§5)'],
    ['Discount creep', '₹3.1 cr', 'Discount 19.3% → 15%', '≈ ₹3.4 cr', 'Recovered, at a small win-rate cost (0.1 pt per pt)']], [2500, 1700, 2300, 1900, 1806]),
  P('Recovered amounts are the Base driver change applied to the FY29 base, so they are approximations, not separate model lines. The plan recovers the three causes that sales and customer success can fix and about a third of the Helix cause. The rest is why NRR stays below 108% (section 4) and why the product decision in D8 matters.', { spacing: { before: 80 } }),

  H1('4. What the plan delivers, and the shortfalls I am defending'),
  img('bridge.png', ...dim('bridge.png')), cap('Exhibit 2. FY26 to FY29 ARR bridge, Base (model: ARR_bridge). Expansion is the second-largest source after direct new logos.'),
  table([['₹ crore', 'FY27', 'FY28', 'FY29'], ['Opening ARR', '310.0', '350.9', '422.7'], ['New logo: direct', '40.0', '55.2', '67.2'], ['New logo: partner-sourced', '3.7', '9.9', '19.7'], ['Expansion', '26.3', '34.4', '46.6'],
    ['Contraction', '(9.8)', '(10.1)', '(11.5)'], ['Churn', '(16.8)', '(17.6)', '(19.2)'], ['Vajra re-tender, expected (Inject 4)', '(2.5)', '–', '–'], ['Closing ARR', '350.9', '422.7', '525.5'], ['Board path', '356.5', '427.8', '521.9'], ['Gap to board path', '(5.6)', '(5.1)', '+3.6'],
    ['NRR / GRR', '99.1% / 90.6%', '101.9% / 92.1%', '103.8% / 92.7%']], [4206, 2000, 2000, 2000], [8]),
  H2('FY27 growth: 13.2% against 15%'),
  P('Three facts make 15% in FY27 hard to buy. Q1 is already set by the pipeline that existed on 1 April (₹8.71 crore forecast, about half of quota). New AEs hired in Q3 produce nothing until their second half-year. And AE capacity binds in the first half: the board path needs 412 qualified deals worked in FY27 against capacity of 380, a gap equal to four fully ramped AEs that cannot be hired and ramped inside the year.'),
  P([B('What would close it. '), 'A win rate three points above plan takes FY27 to 14.9% (section 9). The Aggressive case (the extra ₹3 crore: six more AEs in Q4 and demand generation) reaches 16.2% but its extra spend does not pay back within the 15 months the CFO set in Inject 1. I recommend holding the ₹15 crore envelope, accepting 13.2%, and recovering the path by FY29, which the Base plan does.']),
  H2('NRR: 103.8% against the 108% goal'),
  P('D1 and D5 found that the Helix bundle is a packaging and pricing problem that sales effort alone cannot fix; it was worth ₹34 crore a year, ₹25.6 crore of it in retention. The retention programmes lift NRR from 98.9% to 103.8%. Reaching 108% needs about two more points of churn reduction and two more points of expansion, which I tie to the sensor-agnostic tier (no earlier than Q4 FY27): it lets Helix-incumbent plants keep their Helix sensors and add our analytics. I have not put that effect in the Base plan because the product is not yet built; it is upside, decided in D8.'),
  H2('Partner share: 22.7% against 25%'),
  P('Partner ARR is exactly D6’s plan (₹19.7 crore in FY29), but direct new logos grow faster than D6 assumed, so the share is lower. Reaching 25% needs about ₹22 crore of partner ARR, roughly three more activations in FY28. I would not buy those ahead of evidence: D6’s kill gate at end-Q2 FY28 decides whether the channel scales.'),

  H2('FY27 by quarter: the view the forecast and the Q2 review use'),
  table([['₹ crore', 'Q1 FY27', 'Q2 FY27', 'Q3 FY27', 'Q4 FY27', 'FY27'], ['Direct new logo', '7.97 (locked forecast less partner)', '10.12', '10.73', '11.20', '40.02'], ['Partner-sourced new logo', '0.74', '0.85', '1.00', '1.11', '3.70'],
    ['Expansion', '6.16', '6.41', '6.71', '7.04', '26.31'], ['Contraction + churn', '(6.68)', '(6.64)', '(6.63)', '(6.62)', '(26.57)'], ['Vajra re-tender (expected)', '–', '–', '–', '(2.51)', '(2.51)'], ['Closing ARR', '318.2', '328.9', '340.7', '350.9', '350.9'],
    ['Direct win rate (plan path)', '17.7%', '18.3%', '18.9%', '19.5%', '18.6%'], ['Pipeline required (direct ARR ÷ win rate)', '45.0', '55.3', '56.8', '57.5', '214.5'], ['AEs (end of quarter)', '64', '64', '69', '69', ''],
    ['S&M', '26.8', '28.6', '30.9', '30.9', '117.1'], ['CAC payback (months)', '31.0', '28.9', '29.4', '28.1', '29.3'], ['EBITDA', '(7.9)', '(7.0)', '(6.7)', '(4.3)', '(25.9)']], [3006, 1700, 1300, 1300, 1300, 1600], [6]),

  H1('5. Capacity and pipeline arithmetic'),
  table([['', 'FY27', 'FY28', 'FY29', 'Note'], ['AEs at year end (net new in year)', '69 (+6)', '77 (+8)', '83 (+6)', 'Fractions from attrition timing; guardrail ≤ 76 in FY27'], ['Ramped-AE equivalents (average)', '47.2', '53.7', '61.1', 'FY26: 48.5'],
    ['Effective AE attrition', '24%', '22%', '20%', 'FY26: 29%'], ['AE deal capacity (qualified deals / year)', '380', '450', '534', 'Ramped AEs × 5.4 × 12 ÷ cycle'], ['Qualified pipeline supply (deals / year)', '380', '430', '470', 'D2 tiering and programme reallocation'],
    ['Deals worked / won', '374 / 67', '427 / 89', '470 / 104', 'Binding: AE capacity in H1 FY27, pipeline supply from Q3 FY27'], ['Required direct pipeline = direct ARR ÷ win rate', '₹214.5 cr', '₹265.8 cr', '₹303.9 cr', 'Matches the D4 coverage logic'],
    ['Partner pipeline required vs partner capacity', '₹10.9 / 11.4 cr', '₹29.0 / 30.4 cr', '₹58.0 / 60.8 cr', 'Fits, with little headroom']], [3000, 1300, 1300, 1300, 3306]),
  P([B('The most useful finding in the model: from Q3 FY27, pipeline supply, not AE headcount, limits bookings. '), 'That is why a one-month shorter sales cycle adds only ₹0.6 crore to FY29 ARR, and why AE attrition staying at 29% costs only ₹1.6 crore. It changes the hiring rule: FY28–29 hires are released only when AE capacity use exceeds 90% for two quarters running. In FY29 the plan runs at 88%, so the six FY29 hires are conditional, not committed. A 10% shortfall in qualified pipeline would cost ₹15.4 crore of FY29 ARR and push Q3 FY27 CAC payback to 31 months.'], { spacing: { before: 80 } }),

  H1('6. Profit and loss, gross margin and payback'),
  table([['₹ crore', 'FY26 actual', 'FY27', 'FY28', 'FY29'], ['Revenue (subscription + hardware)', '388.5', '429.6', '511.3', '619.4'], ['Gross margin after partner margin', '68.3%', '68.6%', '67.5%', '67.7%'], ['Partner margin in cost of revenue', '0.4 (in S&M today)', '0.6', '1.9', '4.4'],
    ['S&M (existing lines / all AE pay / initiatives)', '96.0', '117.1 (64.0 / 40.8 / 12.4)', '129.1 (67.8 / 48.8 / 12.5)', '142.0 (71.9 / 56.5 / 13.7)'], ['S&M as % of closing ARR', '31.0%', '33.4%', '30.6%', '27.0%'],
    ['R&D / G&A', '123.3 / 69.4', '131.3 / 72.1', '138.6 / 75.0', '146.9 / 78.0'], ['EBITDA', '(23.3)', '(25.9)', '2.6', '52.6'], ['CAC payback (annual, months)', '26.8', '29.3', '23.1', '18.8']], [3300, 1600, 1800, 1800, 1706], [7]),
  img('cac.png', ...dim('cac.png')), cap('Exhibit 3. Quarterly CAC payback (S&M ÷ ((new + expansion ARR) × gross margin) × 12). Q1 FY27 breaches the 30-month cap; Q3 FY27 is the tightest quarter the plan controls.'),
  P([B('The one guardrail breach. '), 'Q1 FY27 CAC payback is 31.0 months. Bookings for that quarter were fixed by the 1 April pipeline, and nothing approved now can change them; the programmes start in Q2 so they do not add to Q1 spend. I ask the board for an explicit exception for Q1 FY27 only. From Q2 FY27 every quarter is within 30 months, but Q3 FY27 sits at 29.4: a win rate 0.7 points below plan breaks it. That is why the H2 reserve is released only if the Q2 win-rate trigger is met.']),
  P([B('The margin risk nobody has priced. '), 'Hardware sells at about 25% gross margin and attaches to every rupee of new and expansion ARR (₹1.48 of hardware per ₹1 of ARR in FY26, rising from ₹1.34 in FY24). Growth therefore dilutes gross margin. If attach stays at the FY26 level, gross margin falls to 65.9% in FY28 and 64.5% in FY29, breaking the floor. The plan assumes attach falls to ₹1.05 by FY29 through software-led expansion and the sensor-agnostic tier. This is the assumption the CFO should test hardest, and it links the CPO’s sensor-agnostic question in D8 directly to the margin guardrail.']),

  H1('7. Headcount, spend and payback by year'),
  table([['', 'FY27', 'FY28', 'FY29'], ['AEs (end of year)', '69', '77', '83 (6 conditional)'], ['Channel roles (VP + partner managers)', '3', '5', '6'], ['Customer success (retention squads)', '+4, +4 from Q3 if reserve released', '8', '8'],
    ['Value engineer / solutions architect / RevOps / pilot SEs', '1 / 1 / 2 / 3', 'same', 'same'],
    ['Incremental investment (₹ cr)', '14.95', '20.35', '26.55'], ['of which net new AE pay and recruiting', '1.99', '7.83', '12.88'], ['of which channel foundation', '2.44', '3.46', '4.00'], ['of which reserve lines (released at Q2 review)', '2.82', '2.04', '2.16'],
    ['Cumulative investment (₹ cr)', '14.95', '35.30', '61.85'], ['Investment payback vs do-nothing (months)', '30.8', '11.7', '8.0'], ['Investment payback vs FY26-flat (months)', '78.0', '16.5', '10.5']], [4206, 2000, 2000, 2000], [5]),
  P('FY27 alone does not pay back on the stricter test (78 months), because a quarter of the year is gone and hires ramp slowly. The case rests on FY28–29, which is why the Q2 FY27 triggers matter: they are the earliest point at which the board can see whether the FY28 inflection is coming.', { spacing: { before: 80 } }),

  H1('8. Scenarios, sensitivity and break-even'),
  table([['', 'Base', 'Downside', 'Aggressive (₹18 cr)', 'CFO-capped'], ['What changes', 'Recommended', 'Same spend; weaker win, retention, partners', 'Extra ₹3 cr; 12 AEs in FY27', 'Reserve never released; FY28–29 hiring frozen'],
    ['FY29 ARR (₹ cr)', f1(b['ARR FY29']), f1(d['ARR FY29']), f1(a['ARR FY29']), f1(c['ARR FY29'])], ['Growth FY27 / FY28 / FY29', `${pc(b['Growth FY27'])} / ${pc(b['Growth FY28'])} / ${pc(b['Growth FY29'])}`, `${pc(d['Growth FY27'])} / ${pc(d['Growth FY28'])} / ${pc(d['Growth FY29'])}`, `${pc(a['Growth FY27'])} / ${pc(a['Growth FY28'])} / ${pc(a['Growth FY29'])}`, `${pc(c['Growth FY27'])} / ${pc(c['Growth FY28'])} / ${pc(c['Growth FY29'])}`],
    ['NRR FY29', pc(b['NRR FY29']), pc(d['NRR FY29']), pc(a['NRR FY29']), pc(c['NRR FY29'])], ['Lowest gross margin', pc(b['GM min year']), pc(d['GM min year']), pc(a['GM min year']), pc(c['GM min year'])],
    ['Worst CAC payback from Q2 FY27 / Q4 FY28', `${f1(b['CAC worst qtr from Q2 FY27'])} / ${f1(b['CAC Q4 FY28'])}`, `${f1(d['CAC worst qtr from Q2 FY27'])} / ${f1(d['CAC Q4 FY28'])}`, `${f1(a['CAC worst qtr from Q2 FY27'])} / ${f1(a['CAC Q4 FY28'])}`, `${f1(c['CAC worst qtr from Q2 FY27'])} / ${f1(c['CAC Q4 FY28'])}`],
    ['EBITDA FY29 (₹ cr)', f1(b['EBITDA FY29']), f1(d['EBITDA FY29']), f1(a['EBITDA FY29']), f1(c['EBITDA FY29'])], ['Investment FY27 / FY27–29', `${f1(b['Investment FY27'])} / ${f1(b['Investment FY27-29'])}`, `${f1(d['Investment FY27'])} / ${f1(d['Investment FY27-29'])}`, `${f1(a['Investment FY27'])} / ${f1(a['Investment FY27-29'])}`, `${f1(c['Investment FY27'])} / ${f1(c['Investment FY27-29'])}`],
    ['Guardrails failed (incl. Q1 FY27 payback)', '1', '3', '1', '1']], [2500, 1800, 2000, 1950, 1956]),
  P('The Downside is the case to fear: same spend, weak outcomes, ARR ₹419 crore, EBITDA still negative in FY29 and CAC payback above 30 months from Q2 FY27. The triggers in section 12 exist to detect it by the end of Q2 and move to the CFO-capped path, which protects cash at the cost of ₹34 crore of FY29 ARR.', { spacing: { before: 80 } }),
  img('tornado.png', ...dim('tornado.png')), cap('Exhibit 4. FY29 ARR sensitivity, one driver at a time (model: Sensitivity). Win rate and churn dominate; the sales cycle matters only if it gets worse, because pipeline supply binds.'),
  table([['Break-even: the change at which a payback test fails', 'Win rate vs plan', 'Churn vs plan', 'Share of planned improvement delivered'],
    ['CAC payback above 30 months in any quarter from Q2 FY27', `${be['CAC payback > 30 months in any quarter from Q2 FY27 | Win rate (pts)']} pts`, `+${be['CAC payback > 30 months in any quarter from Q2 FY27 | Churn (pts)'].toFixed(1)} pts`, `below ${(be['CAC payback > 30 months in any quarter from Q2 FY27 | Plan delivery (share)'] * 100).toFixed(0)}%`],
    ['CAC payback above 24 months at Q4 FY28', `${be['CAC payback Q4 FY28 > 24 months | Win rate (pts)'].toFixed(1)} pts`, 'does not bind', `below ${(be['CAC payback Q4 FY28 > 24 months | Plan delivery (share)'] * 100).toFixed(0)}%`],
    ['Investment payback above 30 months (vs FY26-flat, FY29)', `${be['Investment payback vs FY26-flat > 30 months (FY29) | Win rate (pts)'].toFixed(1)} pts`, `+${be['Investment payback vs FY26-flat > 30 months (FY29) | Churn (pts)'].toFixed(1)} pts`, `below ${(be['Investment payback vs FY26-flat > 30 months (FY29) | Plan delivery (share)'] * 100).toFixed(0)}%`]], [4200, 1900, 1800, 2306]),
  P([B('Where the investment stops paying back. '), 'The investment as a whole is robust: it keeps paying back within 30 months unless win rate falls eight points below plan (below FY26’s level), churn rises six points, or less than a third of the planned improvement arrives. The payback guardrails are far less forgiving. The every-quarter CAC test fails if win rate is 0.7 points below plan or 78% of the improvement arrives; the 24-month Q4 FY28 test fails at four points or 59%. The plan is therefore more likely to break a guardrail than to destroy value, and the triggers are set against the guardrails.'], { spacing: { before: 80 } }),

  H1('9. Cascade test: win rate plus three points'),
  P('Setting the win-rate shift to 3 in the Assumptions sheet moves every dependent number. The Cascade sheet shows the saved Base, the saved +3 run and the live value side by side.'),
  table([['Metric', 'Where it shows', 'Base', '+3 pts', 'Change'],
    ['Deals won FY27', 'D2 capacity / D4', '67.3', '75.7', '+8.4'], ['Direct new-logo ARR FY27 (₹ cr)', 'D4 forecast', '40.0', '45.0', '+5.0'], ['Direct new-logo ARR Q2 FY27 (₹ cr)', 'D4 next quarter', '10.1', '11.8', '+1.7'],
    ['Pipeline required FY27 (₹ cr)', 'D4 coverage', '214.5', '207.7', '−6.8'], ['Board path FY27: capacity gap (deals)', 'D2 account plan capacity', '(32)', '+28', '+60'], ['Extra ramped AEs needed for board path FY27', 'D2 / hiring', '4.0', '0', '−4.0'],
    ['Partner-sourced ARR FY29 (₹ cr)', 'D6 channel', '19.7', '21.4', '+1.7'], ['Channel saving vs direct FY29 (₹ cr)', 'D6 channel P&L', '11.7', '13.3', '+1.6'], ['Partner share FY29', 'D6 / objective 5', '22.7%', '21.9%', '−0.7 pts'],
    ['Closing ARR FY27 / FY28 / FY29 (₹ cr)', 'D7 bridge', '350.9 / 422.7 / 525.5', '356.3 / 437.0 / 551.4', '+5.4 / +14.4 / +25.9'], ['Growth FY27', 'Guardrail', '13.2%', '14.9%', '+1.7 pts'],
    ['Revenue FY29 (₹ cr)', 'P&L', '619.4', '653.4', '+34.0'], ['Gross margin FY29', 'Guardrail', '67.7%', '67.2%', '−0.5 pts'], ['EBITDA FY27 / FY29 (₹ cr)', 'P&L', '(25.9) / 52.6', '(22.4) / 72.1', '+3.5 / +19.5'],
    ['CAC payback Q4 FY28 (months)', 'Guardrail', '21.2', '19.6', '−1.7'], ['S&M as % of ARR FY29', 'Guardrail', '27.0%', '25.7%', '−1.3 pts'], ['Investment payback vs do-nothing FY29 (months)', 'D8', '8.0', '6.8', '−1.2'],
    ['Unchanged: AE capacity, NRR, partner pipeline required, Q1 FY27', 'Explained', '', '', 'Capacity does not depend on win rate; NRR is existing customers; Q1 is locked']], [3400, 1900, 1700, 1700, 1506]),
  P('Three second-order effects are worth saying aloud: partner share falls slightly because direct grows faster; gross margin dips because more new ARR brings more low-margin hardware; and three points of win rate would almost close the FY27 gap on its own.', { spacing: { before: 80 } }),

  H1('10. Inject 4: Vajra Auto Components re-tender (₹9.5 crore, renewal Q4 FY27)'),
  P('Vajra is a top-five customer and 3.1% of ARR. It is a Helix-incumbent plant, HelixAsset is free to Helix customers until 31 March 2027 (Inject 2), and the Helix bundle is the largest churn driver in D1. Without a plan I put the chance of losing it at 45%, with a 15% price concession if we keep it reactively.'),
  table([['', 'Q4 FY27 ARR lost (₹ cr)', 'FY27 closing ARR (₹ cr)', 'FY27 NRR', 'FY27 growth'], ['Expected, with retention plan (20% loss, 8% concession)', '2.5', '350.9', '99.1%', '13.2%'],
    ['Retained at 8% concession', '0.8', '352.7', '99.7%', '13.8%'], ['Lost', '9.5', '344.0', '96.9%', '11.0%'], ['Expected, without a plan (45% loss, 15% concession)', '5.1', '348.4', '98.3%', '12.4%']], [4200, 1500, 1600, 1400, 1506], [1]),
  P([B('Retention plan (₹0.9 crore from the reserve, released now as a defensive item). '), 'CEO and CRO meet Vajra’s MD and CFO by week 10 to shape the re-tender criteria; a business review built from Vajra’s own usage data (assets monitored, failures caught, downtime avoided, using the D3 value model); a three-year renewal with price lock and an 8% concession inside the D5 15% limit, plus expansion to its two uncovered plants; the MES integration pack and a named executive sponsor; and no matching of “free”, since HelixAsset’s free period ends on 31 March 2027. Expected ARR saved is ₹2.55 crore for ₹0.9 crore, a payback of about six months.'], { spacing: { before: 80 } }),
  P([B('Effect on the forecast. '), 'Q4 FY27 net ARR added is ₹10.2 crore expected, ₹12.0 crore if Vajra renews and ₹3.2 crore if it leaves. The D4 forecast process treats Vajra as a named line from Q3 FY27, reported separately from new-logo bookings. Losing Vajra costs about 2.3 points of FY27 NRR and ₹7.4 crore of FY29 ARR.']),

  H1('11. Sequencing by quarter'),
  table([['When', 'What starts or is decided', 'Headcount and spend'],
    ['Q1 FY27 (Apr–Jun, under way)', 'D4 forecast rules and hygiene flags live; CRM cleaning rules (D1); D2 tiers applied to territories; discount cap 15% with CFO approval above; battlecards v1.1 (Inject 2); P05/P11 restricted (Inject 3); VP Channel search', 'No new spend; Q1 locked at ₹8.71 cr forecast'],
    ['Q2 FY27 (Jul–Sep)', 'Retention squad and adoption programme; Helix renewal protection; top-30 expansion programme; value-selling training and value engineer; pilot SEs; RevOps; AE retention pool; sign PR01, PR02, PR06; partner manager 1; Vajra executive meeting and business review; Q2 review gate (15 Oct)', '₹10.1 cr of FY27 programme budget starts (excl. AE pay and reserve); 4 CSMs, 1 value engineer, 1 architect, 2 RevOps, 2 SEs, VP Channel'],
    ['Q3 FY27 (Oct–Dec)', 'Six AEs start (SEA-weighted); reserve released if triggers met: second retention squad, SE pilot capacity; partner manager 2; PR07 signed; Vajra three-year offer', '+6 AEs; +4 CSMs, +1 SE (if released)'],
    ['Q4 FY27 (Jan–Mar)', 'Vajra decision; HelixAsset free period ends 31 Mar 2027: Helix-incumbent win-back campaign; sensor-agnostic tier go/no-go with cannibalisation guard (D8); FY28 hiring released against the 90% capacity-use rule', 'FY27 total ₹14.95 cr'],
    ['FY28', '8 AEs (Q1, Q3); 9 partner activations; channel kill gate at end-Q2; CAC payback ≤ 24 months by Q4', '₹20.4 cr; 5 channel roles'],
    ['FY29', '6 AEs, conditional on capacity use; 5 partner activations; review of NRR programme against 108%', '₹26.6 cr; 6 channel roles']], [1900, 5406, 2900]),

  H1('12. Risks and early-warning triggers'),
  table([['Risk', 'Probability', 'FY29 ARR impact (model)', 'Mitigation and fallback'],
    ['Helix pressure deeper than planned (churn 2 pts higher)', 'Medium (35%)', '−₹23 cr', 'Second retention squad; Helix win-back from Apr 2027; sensor-agnostic tier. Fallback: CFO-capped path'],
    ['Win-rate programme stalls (3 pts below plan)', 'Medium (30%)', '−₹26 cr; CAC breach from 0.7 pts', 'Q2 trigger holds the H2 reserve; SEs redeployed to Tier 1 deals'],
    ['Qualified pipeline 10% below supply plan', 'Medium (30%)', '−₹15 cr; Q3 FY27 CAC 31 months', 'Programme budget moves to strategic/scaled tiers; FY28 hiring held'],
    ['Hardware attach does not fall', 'Medium (35%)', 'None on ARR; GM 65.9% (FY28), 64.5% (FY29)', 'Hardware pricing floor; software-led expansion bundles; sensor-agnostic tier'],
    ['Partners perform like FY26 India partners', 'Low–medium (25%)', '−₹8 cr at −30% productivity', 'D6 kill gate at end-Q2 FY28'],
    ['Vajra lost', 'Low (20%)', '−₹7.4 cr; FY27 NRR −2.3 pts', 'Retention plan; exec sponsor; reference accounts'],
    ['AE attrition stays at 29%', 'Medium (40%)', '−₹1.6 cr (pipeline binds)', 'Retention pool; slower backfill is tolerable']], [3000, 1300, 2200, 3706]),
  H2('Triggers for Q1 and Q2 FY27 (review dates 15 July and 15 October 2026)'),
  table([['Programme', 'Leading indicator', 'Q1 threshold', 'Q2 threshold', 'If missed at Q2'],
    ['Targeting', 'Share of AE touches in strategic and scaled tiers', '≥ 55%', '≥ 70%', 'Reassign territories; freeze low-touch AE activity'],
    ['Win rate and price', 'Qualified win rate (rolling two quarters); average discount on wins', '≥ 17.5%; ≤ 18.5%', '≥ 18.0%; ≤ 18%', 'Hold H2 reserve (₹1.92 cr); redeploy SEs'],
    ['Pipeline supply', 'New qualified direct deals created', '≥ 90', '≥ 95', 'Move programme budget; delay Q3 hires'],
    ['Forecast', 'Actual vs D4 forecast', 'Q1 within ±15% of ₹8.71 cr', 'Q2 within ±15%', 'Recalibrate; review Commit rules'],
    ['Retention', 'Churn + contraction; Helix-incumbent renewals kept by value', '≤ ₹6.8 cr; ≥ 85%', 'H1 ≤ ₹13.5 cr; ≥ 85%', 'Release second squad early (if win trigger met) or cut expansion spend'],
    ['Expansion', 'Expansion ARR', '≥ ₹6.0 cr', 'H1 ≥ ₹12.5 cr', 'Re-scope top-30 programme'],
    ['Vajra (Inject 4)', 'Executive meeting; business review; shortlist status', 'Meeting by week 10', 'Review delivered; not shortlisted on price alone', 'CEO escalation with three-year offer'],
    ['AE capacity', 'Annualised AE attrition; offers accepted for Q3 start', '≤ 27%', '≤ 26%; 6 offers by 31 Aug', 'Retention pool review; do not over-hire (pipeline binds)'],
    ['Channel (D6)', 'Partners signed; registered partner pipeline; P05/P11 Helix-account registrations', '—', '3 signed; ≥ ₹6 cr; 0', 'Stop wave-2 recruiting'],
    ['Payback', 'Quarterly CAC payback', 'Reported (exception)', '≤ 30 months', 'Move to CFO-capped path'],
    ['Sensor-agnostic tier', 'Readiness: cannibalisation test design, 3 pilot plants signed', 'Design approved', '3 pilots signed', 'Defer launch beyond Q4 FY27']], [1500, 2800, 1700, 1900, 2306]),
  P([B('Continue, adjust or stop. '), 'All Q2 thresholds met: release the reserve and continue. Win-rate or pipeline thresholds missed: hold the reserve (CFO-capped path) and adjust. Win rate below 17% and CAC payback above 32 months at Q2: stop the Q3 hires and return to the board.'], { spacing: { before: 80 } }),

  H1('13. What the company stops doing'),
  bul([B('Stop sending AEs to the 1,600 low-touch accounts. '), 'They took 62% of AE touches and produced 12% of won ARR (D2). They move to SDRs, inside sales, marketing and partners.']),
  bul([B('Stop discounting above 15% without CFO approval, and stop matching “free”. '), 'Discount creep bought little win rate (D1, D5); Inject 2 is answered with a three-year value case, not a price match.']),
  bul([B('Stop calling a deal Commit before stage 5. '), 'Commit calls missed by 27% on average (D4); the forecast now uses the calibrated model and the new category rules.']),
  bul([B('Stop planning on a six-month AE ramp and quota without ramp relief. '), 'Measured ramp is 12–24 months to full productivity (D1); quota for new AEs is prorated on the ramp weights in this model.']),
  bul([B('Stop keeping dormant partners and booking partner margin in S&M. '), 'Five partners exit (D6); partner margin is charged to gross margin so the 66% floor is tested honestly.']),
  bul([B('Stop hiring AEs to quota. '), 'From Q3 FY27, pipeline supply binds; hires are released only when AE capacity use exceeds 90% for two quarters.']),

  H1('14. Limits of the evidence, and the assumption I am least sure of'),
  P([B('Least sure: the hardware attach rate falling from ₹1.48 to ₹1.05 per rupee of new and expansion ARR. '), 'It is not a sales assumption, it has no direct evidence in the data room beyond the FY24–26 trend (which is rising, not falling), and it alone decides whether the 66% gross margin floor holds in FY28–29. If it does not fall, the plan still grows ARR but breaks the margin guardrail, and the sensor-agnostic tier becomes a margin necessity rather than an option.']),
  bul([B('Driver sizes are judgements. '), 'The model links each programme to a driver, but how far each driver moves rests on D1–D6 evidence, not on a controlled test. The “share of plan delivered” lever shows how much can be missed before each payback test fails (section 8).']),
  bul([B('Primary evidence is incomplete. '), 'The eight structured interviews and the five external benchmarks the brief requires are in progress; assumptions that rest on interview codes (discount response, sensor reuse) are flagged in Appendix A until the interviews are coded.']),
  bul([B('Synthetic data. '), 'All figures come from a synthetic data room. Where the data contradicted the brief (for example, the 24% forecast miss is against reported, not cleaned, bookings), the data was used and the difference stated.']),
  bul([B('The hold-out test is still to come. '), 'The Q1 FY27 forecast (₹8.71 crore) is locked and will be scored against actuals after D8. If it misses by more than 15%, the Q1 anchor in this model and the calibration factor are revisited.']),

  H1('15. Owning and running the model'),
  P('RevOps owns the workbook. Actuals replace plan quarter by quarter in the ARR bridge; the Checks sheet must show zero errors before any number leaves the building. Every board or CFO figure is a view of this model, not a private spreadsheet. Changes to Base assumptions need CRO and CFO sign-off and are logged on the Traceability sheet. The model is re-run for all four scenarios at each quarterly review, and the saved-run sheets (Scenarios, Sensitivity, Cascade) are regenerated with run_scenarios.py so that the saved and live numbers never drift apart.'),

  new Paragraph({ children: [new PageBreak()] }),
  H1('Appendix A. Traceability map'),
  table([['Assumption', 'Base value', 'Source', 'From'],
    ['Opening ARR and FY26 bridge', '₹310 cr; +41, +22, −9, −16', 'DR3 P&L; DR2 ARR movements', 'D1'], ['Direct win rate FY26', '17.1%', 'DR1 cleaned (duplicates, tests, DQ-as-lost removed)', 'D1'],
    ['Win-rate path', '19.5 / 21.5 / 22.5%', 'D2 tier mix (+2.9 pts); D5 (+0.6 pts beyond D2); Inject 2 Helix floor 7%', 'D2, D5'], ['Sales cycle', '8.1 → 7.3 months', 'DR1 stage history; D4 stage-exit rules; D3', 'D1, D3, D4'],
    ['Deal size and discount', '₹71.4 → 77 lakh list; 19.3% → 15%', 'DR1 FY26 wins; D3 negotiation plan; D5 limits', 'D3, D5'], ['Win-rate response to discount', '0.1 pt per pt', 'D1 discount-creep test; D5 interview code (to validate)', 'D1, D5'],
    ['Qualified pipeline supply', '380 / 430 / 470', 'DR1 FY26 392; D2 tiering and ₹24 cr reallocation', 'D2'], ['Deals carried per ramped AE', '5.4', 'DR3 ae_quarterly × DR1 closes and cycle', 'D1, D2'],
    ['Ramp weights', '0 / 0.33 / 0.66 / 1.0', 'D1 productivity by tenure (DR3)', 'D1'], ['AE attrition', '29% → 24 / 22 / 20%', 'DR3 roster; Inject 1 retention pool', 'D1, Inject 1'],
    ['Net new AEs', '6 / 8 / 6', 'Inject 1; guardrail ≤ 12', 'Inject 1'], ['Q1 FY27 new logo', '₹8.71 cr', 'D4 locked forecast (sha256 ba5b63ad…)', 'D4'],
    ['Partner activations, productivity, ramp', '8 / 9 / 5; ₹1.2 cr; 15 / 60 / 100%', 'DR6; D1 SEA partner win 34%', 'D6'], ['Existing partner ARR after Inject 3', '₹2.26 cr', 'DR1 open pipeline; P05/P11 haircut', 'D6'],
    ['Partner margins; channel fixed cost', '16–18%; ₹2.44 / 3.46 / 4.0 cr', 'D6 programme; DR3 partner-manager cost', 'D6'], ['Expansion / contraction / churn', '8.5→10.5% / 3.0→2.5% / 5.0→4.0%', 'DR2, DR3; D1 NRR diagnosis; Inject 1; Inject 2', 'D1'],
    ['Vajra', '20% loss; 8% concession', 'Inject 4; DR2 CU-1095; D5', 'D7'], ['Hardware attach', '1.48 → 1.05', 'DR3 FY24–26; D1 SENSOR-REUSE code', 'D1, D8'],
    ['Cost of revenue', 'Software 18%; hardware 75%', 'DR3', 'DR3'], ['S&M base; AE cost; recruiting', '₹60.3 cr; ₹0.56 cr; ₹3.5 lakh', 'DR3 S&M by line; unit costs', 'DR3'],
    ['Investment lines FY27', '₹14.95 cr', 'Inject 1 envelope', 'Inject 1'], ['R&D / G&A growth', '6% / 4%', 'Assumption (no new hardware)', 'D7'],
    ['Do-nothing trends', 'New logo −5%/yr; NRR −1 pt/yr', 'D1 FY24–26 trends', 'D1'], ['Guardrails; CAC definition', 'Brief §4, §6; DR3 definitions', 'Brief; DR3', '—'],
    ['Primary evidence', '8 interviews (in progress)', 'Interview kit and log; interview-based assumptions flagged until coded', 'Kit']], [2700, 2300, 3806, 1400]),
  H1('Appendix B. Checks sheet (Base)'),
  table([['Check', 'Value', 'Result'], ['ARR bridge ties every quarter', '0.000', 'OK'], ['No formula errors in model sheets', '0', 'OK'], ['New logo = direct + partner (counted once)', '0.000', 'OK'],
    ['Investment within FY27 envelope', '₹14.95 cr of ₹15 cr', 'OK'], ['Gross margin ≥ 66% (lowest year)', '67.5%', 'OK'], ['CAC payback ≤ 30 months, worst quarter', '31.0 (Q1 FY27)', 'BREACH: exception requested'],
    ['CAC payback ≤ 24 months by Q4 FY28', '21.2', 'OK'], ['S&M ≤ 30% of ARR by FY29', '27.0%', 'OK'], ['Net new AEs FY27 ≤ 12; headcount ≤ 76', '6; 69', 'OK'], ['Channel roles ≤ 6', '3', 'OK'],
    ['Pipeline: deals worked ≤ AE capacity and ≤ supply, every quarter', '0 exceptions', 'OK'], ['Partner pipeline ≤ partner capacity', '0 exceptions', 'OK'], ['Growth FY27 / FY28 / FY29', '13.2% / 20.4% / 24.3%', 'FY27 SHORTFALL (defended)'],
    ['NRR FY29 vs 108%', '103.8%', 'SHORTFALL (defended)'], ['Partner share FY29 vs 25%', '22.7%', 'SHORTFALL (defended)'], ['D6 reconciliation: partner ARR FY27–29 = ₹33.27 cr', '₹33.27 cr', 'OK']], [5600, 2400, 2206], [6]),
  P([r('External benchmarks (five independent sources required by the brief) are still to be added from the student’s own research; the DR8 ranges were not used as inputs.', { italics: true, size: 16, color: '52514E' })], { spacing: { before: 80 } }),
];
const doc = new Document({ styles: { default: { document: { run: { font: 'Arial', size: 21 } } },
    paragraphStyles: [{ id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 24, bold: true, color: '1F3A5F' }, paragraph: { spacing: { before: 180, after: 70 } } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 20, bold: true, color: '1F3A5F' }, paragraph: { spacing: { before: 110, after: 50 } } }] },
  numbering: { config: [{ reference: 'b', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 360, hanging: 240 } } } }] }] },
  sections: [{ properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 850, bottom: 850, left: 850, right: 850 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [r('D7 plan memo · page ', { size: 14, color: '8A8984' }), new TextRun({ children: [PageNumber.CURRENT], size: 14, color: '8A8984' })] })] }) }, children: kids }] });
Packer.toBuffer(doc).then(buf => { fs.writeFileSync('out/D7_Plan_Memo.docx', buf); console.log('ok'); });
